import sys
from pathlib import Path

block_cipher = None

PROJ = Path(SPECPATH)

a = Analysis(
    [str(PROJ / "server.py")],
    pathex=[str(PROJ)],
    binaries=[],
    datas=[],
    hiddenimports=[
        # local packages
        "context",
        "executor",
        "scope",
        "findings",
        "tools",
        "tools._utils",
        "tools.recon",
        "tools.web",
        "tools.creds",
        "tools.exploit",
        "tools.generic",
        "tools.session",
        "parsers",
        "parsers.nmap",
        "parsers.gobuster",
        "parsers.ffuf",
        "parsers.hydra",
        "parsers.john",
        "parsers.nikto",
        "parsers.sqlmap",
        "parsers.enum4linux",
        # mcp server stack
        "mcp",
        "mcp.types",
        "mcp.server",
        "mcp.server.fastmcp",
        "mcp.server.fastmcp.server",
        "mcp.server.fastmcp.tools",
        "mcp.server.fastmcp.tools.tool_manager",
        "mcp.server.fastmcp.resources",
        "mcp.server.fastmcp.resources.resource_manager",
        "mcp.server.fastmcp.prompts",
        "mcp.server.fastmcp.utilities",
        "mcp.server.fastmcp.utilities.types",
        "mcp.server.lowlevel",
        "mcp.server.lowlevel.server",
        "mcp.server.lowlevel.func_inspection",
        "mcp.server.lowlevel.helper_types",
        "mcp.server.session",
        "mcp.server.stdio",
        "mcp.server.models",
        "mcp.shared.session",
        "mcp.shared.context",
        "mcp.shared.exceptions",
        "mcp.shared.message",
        "mcp.shared.memory",
        "mcp.shared.version",
        "mcp.shared.tool_name_validation",
        "mcp.shared.metadata_utils",
        "mcp.shared.auth",
        "mcp.shared.auth_utils",
        # async runtime
        "anyio",
        "anyio._backends._asyncio",
        "anyio.streams.memory",
        # serialization / validation
        "pydantic",
        "pydantic.v1",
        "pydantic_settings",
        "jsonschema",
        "jsonschema.validators",
        "jsonschema._validators",
        "jsonschema._legacy_validators",
        "jsonschema.exceptions",
        # http / transport (fastmcp needs these even for stdio)
        "httpx",
        "httpx._transports.default",
        "starlette",
        "starlette.applications",
        "starlette.routing",
        "uvicorn",
        "uvicorn.config",
        "uvicorn.main",
        # yaml
        "yaml",
        # stdlib extras that dynamic imports may miss
        "ipaddress",
        "xml.etree.ElementTree",
        "importlib.metadata",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "unittest",
        "PyQt5",
        "PySide6",
        "PyQt6",
        "PySide2",
        "matplotlib",
        "IPython",
        "notebook",
        "PIL",
        "numpy",
    ],
    noarchive=False,
    cipher=block_cipher,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="kali-mcp",
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=False,          # UPX can trip AV; disable unless you specifically want it
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    onefile=True,
)
